# !!!! YOU NEED TO CHANGE THIS !!!!
# This is the connection string for your database
ConnStr = "dbname=gnorm-db host=127.0.0.1 sslmode=disable user=gnorm-user password=password"

DBType = "postgres"

Schemas = ["public","product_catalog"]

PostRun = ["goimports", "-w", "$GNORMFILE"]

NameConversion = "{{pascal .}}"

# This will output the files in a subdirectory called "gnorm".  You can change
# this, but if you do, change the RootPkg definition below to match what the
# package name should be.
OutputDir = "./generated"

ExcludeTables = ["schema_version"]

PluginDirs = ["./gnorm_templates/plugin"]

[Params]
# RootPkg is the package declaration for the output dir. It should match the
# directory name above. You may change this as appropriate.
RootPkg = "generated"

# !!! You need to change this!
# RootImport is the import path for the output directory.
RootImport = "github.com/gnormal/postgres-go/generated"

[SchemaPaths]
"fields.go" = "gnorm_templates/fields.gotmpl"
"db.go" = "gnorm_templates/db.gotmpl"

[TablePaths]
"{{toLower .Schema}}/{{toLower .Table}}/{{toLower .Table}}.go" = "gnorm_templates/table.gotmpl"

[EnumPaths]
"{{toLower .Schema}}/enum/{{toLower .Enum}}.go" = "gnorm_templates/enum.gotmpl"

[TypeMap]
"timestamp with time zone" = "time.Time"
"timestamptz" = "time.Time"
"varchar" = "string"
"text" = "string"
"boolean" = "bool"
# from "github.com/gofrs/go.uuid"
"uuid" = "uuid.UUID"
"character varying" = "string"
"character" = "string"
"smallint" = "int"
"integer" = "int"
"int4" = "int32"
"int8" = "int64"
"numeric" = "float64"
"bigint" = "int64"
# from "github.com/lib/pq/hstore"
"hstore" = "hstore.Hstore"
# note that the package name here has to be kept in sync with the RootPkg above.
"jsonb" = "generated.Jsonb"
# the package name here needs to be kept in sync with the enum template's package name
"bytea" = "generated.Bytea"
"book_type" = "enum.BookType"

[NullableTypeMap]
"timestamp with time zone" = "pq.NullTime"
"text" = "sql.NullString"
"boolean" = "sql.NullBool"
"uuid" = "uuid.NullUUID"
"character varying" = "sql.NullString"
"character" = "sql.NullString"
"integer" = "sql.NullInt64"
"numeric" = "sql.NullFloat64"
"hstore" = "hstore.Hstore"
# note that the package name here has to be kept in sync with the RootPkg above.
"jsonb" = "generated.Jsonb"
